language : python
python :
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - psql -c 'create database stores_testdb' -U postgres
script:
  -  py.test --cov=app tests/
  - coveralls
after_success:
 - coveralls